version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "php artisan migrate && php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
            -   /app/vendor
        ports:
            - 8001:8000
        depends_on:
            main_db:
                condition: service_healthy

    main_queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            main_db:
                condition: service_healthy

    main_db:
        image: mysql:5.7.22
        healthcheck:
            test: [ "CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B' ]
            interval: 30s
            timeout: 10s
            retries: 4
        environment:
            MYSQL_DATABASE: micro_main
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3309:3306
        volumes:
            - ./storage/dbdata:/var/lib/mysql

    phpmyadmin:
        depends_on:
            main_db:
                condition: service_healthy
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: main_db
            PMA_USER: root
            PMA_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
